[package]
name = "sqlx-seeder"
version = "0.1.2"
edition = "2018"
description = "seederの作成"
license = "MIT"
documentation = "https://docs.rs/sqlx_seeder/"

[[bin]]
name = "sqlx-seeder:seeder"
path = "src/bin/seeder.rs"

[dependencies]
